module DeliveryMessage
  NotExit ='运单不存在'
  AddForkliftSuccess='添加清单成功'
  CheckForkliftFailed='托清单不存在或已经加入都其他运单中'
  DeleteForkliftSuccess='删除清单成功'
  DeleteForkliftFailed='删除清单失败'
  CannotUpdate='不能修改'
  CannotDelete='不能删除'
  ForkliftHasNotExist='不是所有的托清单都存在'
  ForkliftExistInOthers = '托清单已经存在运单中,不能创建'
  SendSuccess='发送成功'
  SendFailed='发送失败'
  NetworkNotGood=',网络不通畅，请导出运单!'
  DeleteSuccess='删除成功'
  DeleteFailed='删除失败'
  UpdateSuccess='修改成功'
  UpdateFailed='修改失败'
  AlreadyReceived='已接收'
  ReceiveSuccess='接收成功'
  ReceiveFailed='接收失败'
  NotSend=',运单未发送,请联系发货人员发货'
end