require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DockPointsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DockPoint. As you add validations to DockPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DockPointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dock_points as @dock_points" do
      dock_point = DockPoint.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:dock_points)).to eq([dock_point])
    end
  end

  describe "GET #show" do
    it "assigns the requested dock_point as @dock_point" do
      dock_point = DockPoint.create! valid_attributes
      get :show, {:id => dock_point.to_param}, valid_session
      expect(assigns(:dock_point)).to eq(dock_point)
    end
  end

  describe "GET #new" do
    it "assigns a new dock_point as @dock_point" do
      get :new, {}, valid_session
      expect(assigns(:dock_point)).to be_a_new(DockPoint)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dock_point as @dock_point" do
      dock_point = DockPoint.create! valid_attributes
      get :edit, {:id => dock_point.to_param}, valid_session
      expect(assigns(:dock_point)).to eq(dock_point)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new DockPoint" do
        expect {
          post :create, {:dock_point => valid_attributes}, valid_session
        }.to change(DockPoint, :count).by(1)
      end

      it "assigns a newly created dock_point as @dock_point" do
        post :create, {:dock_point => valid_attributes}, valid_session
        expect(assigns(:dock_point)).to be_a(DockPoint)
        expect(assigns(:dock_point)).to be_persisted
      end

      it "redirects to the created dock_point" do
        post :create, {:dock_point => valid_attributes}, valid_session
        expect(response).to redirect_to(DockPoint.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dock_point as @dock_point" do
        post :create, {:dock_point => invalid_attributes}, valid_session
        expect(assigns(:dock_point)).to be_a_new(DockPoint)
      end

      it "re-renders the 'new' template" do
        post :create, {:dock_point => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dock_point" do
        dock_point = DockPoint.create! valid_attributes
        put :update, {:id => dock_point.to_param, :dock_point => new_attributes}, valid_session
        dock_point.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dock_point as @dock_point" do
        dock_point = DockPoint.create! valid_attributes
        put :update, {:id => dock_point.to_param, :dock_point => valid_attributes}, valid_session
        expect(assigns(:dock_point)).to eq(dock_point)
      end

      it "redirects to the dock_point" do
        dock_point = DockPoint.create! valid_attributes
        put :update, {:id => dock_point.to_param, :dock_point => valid_attributes}, valid_session
        expect(response).to redirect_to(dock_point)
      end
    end

    context "with invalid params" do
      it "assigns the dock_point as @dock_point" do
        dock_point = DockPoint.create! valid_attributes
        put :update, {:id => dock_point.to_param, :dock_point => invalid_attributes}, valid_session
        expect(assigns(:dock_point)).to eq(dock_point)
      end

      it "re-renders the 'edit' template" do
        dock_point = DockPoint.create! valid_attributes
        put :update, {:id => dock_point.to_param, :dock_point => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dock_point" do
      dock_point = DockPoint.create! valid_attributes
      expect {
        delete :destroy, {:id => dock_point.to_param}, valid_session
      }.to change(DockPoint, :count).by(-1)
    end

    it "redirects to the dock_points list" do
      dock_point = DockPoint.create! valid_attributes
      delete :destroy, {:id => dock_point.to_param}, valid_session
      expect(response).to redirect_to(dock_points_url)
    end
  end

end
