require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PartWrappagesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PartWrappage. As you add validations to PartWrappage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PartWrappagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all part_wrappages as @part_wrappages" do
      part_wrappage = PartWrappage.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:part_wrappages)).to eq([part_wrappage])
    end
  end

  describe "GET #show" do
    it "assigns the requested part_wrappage as @part_wrappage" do
      part_wrappage = PartWrappage.create! valid_attributes
      get :show, {:id => part_wrappage.to_param}, valid_session
      expect(assigns(:part_wrappage)).to eq(part_wrappage)
    end
  end

  describe "GET #new" do
    it "assigns a new part_wrappage as @part_wrappage" do
      get :new, {}, valid_session
      expect(assigns(:part_wrappage)).to be_a_new(PartWrappage)
    end
  end

  describe "GET #edit" do
    it "assigns the requested part_wrappage as @part_wrappage" do
      part_wrappage = PartWrappage.create! valid_attributes
      get :edit, {:id => part_wrappage.to_param}, valid_session
      expect(assigns(:part_wrappage)).to eq(part_wrappage)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PartWrappage" do
        expect {
          post :create, {:part_wrappage => valid_attributes}, valid_session
        }.to change(PartWrappage, :count).by(1)
      end

      it "assigns a newly created part_wrappage as @part_wrappage" do
        post :create, {:part_wrappage => valid_attributes}, valid_session
        expect(assigns(:part_wrappage)).to be_a(PartWrappage)
        expect(assigns(:part_wrappage)).to be_persisted
      end

      it "redirects to the created part_wrappage" do
        post :create, {:part_wrappage => valid_attributes}, valid_session
        expect(response).to redirect_to(PartWrappage.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved part_wrappage as @part_wrappage" do
        post :create, {:part_wrappage => invalid_attributes}, valid_session
        expect(assigns(:part_wrappage)).to be_a_new(PartWrappage)
      end

      it "re-renders the 'new' template" do
        post :create, {:part_wrappage => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested part_wrappage" do
        part_wrappage = PartWrappage.create! valid_attributes
        put :update, {:id => part_wrappage.to_param, :part_wrappage => new_attributes}, valid_session
        part_wrappage.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested part_wrappage as @part_wrappage" do
        part_wrappage = PartWrappage.create! valid_attributes
        put :update, {:id => part_wrappage.to_param, :part_wrappage => valid_attributes}, valid_session
        expect(assigns(:part_wrappage)).to eq(part_wrappage)
      end

      it "redirects to the part_wrappage" do
        part_wrappage = PartWrappage.create! valid_attributes
        put :update, {:id => part_wrappage.to_param, :part_wrappage => valid_attributes}, valid_session
        expect(response).to redirect_to(part_wrappage)
      end
    end

    context "with invalid params" do
      it "assigns the part_wrappage as @part_wrappage" do
        part_wrappage = PartWrappage.create! valid_attributes
        put :update, {:id => part_wrappage.to_param, :part_wrappage => invalid_attributes}, valid_session
        expect(assigns(:part_wrappage)).to eq(part_wrappage)
      end

      it "re-renders the 'edit' template" do
        part_wrappage = PartWrappage.create! valid_attributes
        put :update, {:id => part_wrappage.to_param, :part_wrappage => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested part_wrappage" do
      part_wrappage = PartWrappage.create! valid_attributes
      expect {
        delete :destroy, {:id => part_wrappage.to_param}, valid_session
      }.to change(PartWrappage, :count).by(-1)
    end

    it "redirects to the part_wrappages list" do
      part_wrappage = PartWrappage.create! valid_attributes
      delete :destroy, {:id => part_wrappage.to_param}, valid_session
      expect(response).to redirect_to(part_wrappages_url)
    end
  end

end
