require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PtlJobsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PtlJob. As you add validations to PtlJob, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PtlJobsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ptl_jobs as @ptl_jobs" do
      ptl_job = PtlJob.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ptl_jobs)).to eq([ptl_job])
    end
  end

  describe "GET #show" do
    it "assigns the requested ptl_job as @ptl_job" do
      ptl_job = PtlJob.create! valid_attributes
      get :show, {:id => ptl_job.to_param}, valid_session
      expect(assigns(:ptl_job)).to eq(ptl_job)
    end
  end

  describe "GET #new" do
    it "assigns a new ptl_job as @ptl_job" do
      get :new, {}, valid_session
      expect(assigns(:ptl_job)).to be_a_new(PtlJob)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ptl_job as @ptl_job" do
      ptl_job = PtlJob.create! valid_attributes
      get :edit, {:id => ptl_job.to_param}, valid_session
      expect(assigns(:ptl_job)).to eq(ptl_job)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PtlJob" do
        expect {
          post :create, {:ptl_job => valid_attributes}, valid_session
        }.to change(PtlJob, :count).by(1)
      end

      it "assigns a newly created ptl_job as @ptl_job" do
        post :create, {:ptl_job => valid_attributes}, valid_session
        expect(assigns(:ptl_job)).to be_a(PtlJob)
        expect(assigns(:ptl_job)).to be_persisted
      end

      it "redirects to the created ptl_job" do
        post :create, {:ptl_job => valid_attributes}, valid_session
        expect(response).to redirect_to(PtlJob.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ptl_job as @ptl_job" do
        post :create, {:ptl_job => invalid_attributes}, valid_session
        expect(assigns(:ptl_job)).to be_a_new(PtlJob)
      end

      it "re-renders the 'new' template" do
        post :create, {:ptl_job => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ptl_job" do
        ptl_job = PtlJob.create! valid_attributes
        put :update, {:id => ptl_job.to_param, :ptl_job => new_attributes}, valid_session
        ptl_job.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ptl_job as @ptl_job" do
        ptl_job = PtlJob.create! valid_attributes
        put :update, {:id => ptl_job.to_param, :ptl_job => valid_attributes}, valid_session
        expect(assigns(:ptl_job)).to eq(ptl_job)
      end

      it "redirects to the ptl_job" do
        ptl_job = PtlJob.create! valid_attributes
        put :update, {:id => ptl_job.to_param, :ptl_job => valid_attributes}, valid_session
        expect(response).to redirect_to(ptl_job)
      end
    end

    context "with invalid params" do
      it "assigns the ptl_job as @ptl_job" do
        ptl_job = PtlJob.create! valid_attributes
        put :update, {:id => ptl_job.to_param, :ptl_job => invalid_attributes}, valid_session
        expect(assigns(:ptl_job)).to eq(ptl_job)
      end

      it "re-renders the 'edit' template" do
        ptl_job = PtlJob.create! valid_attributes
        put :update, {:id => ptl_job.to_param, :ptl_job => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ptl_job" do
      ptl_job = PtlJob.create! valid_attributes
      expect {
        delete :destroy, {:id => ptl_job.to_param}, valid_session
      }.to change(PtlJob, :count).by(-1)
    end

    it "redirects to the ptl_jobs list" do
      ptl_job = PtlJob.create! valid_attributes
      delete :destroy, {:id => ptl_job.to_param}, valid_session
      expect(response).to redirect_to(ptl_jobs_url)
    end
  end

end
