require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ScrapListItemsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ScrapListItem. As you add validations to ScrapListItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScrapListItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all scrap_list_items as @scrap_list_items" do
      scrap_list_item = ScrapListItem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:scrap_list_items)).to eq([scrap_list_item])
    end
  end

  describe "GET #show" do
    it "assigns the requested scrap_list_item as @scrap_list_item" do
      scrap_list_item = ScrapListItem.create! valid_attributes
      get :show, {:id => scrap_list_item.to_param}, valid_session
      expect(assigns(:scrap_list_item)).to eq(scrap_list_item)
    end
  end

  describe "GET #new" do
    it "assigns a new scrap_list_item as @scrap_list_item" do
      get :new, {}, valid_session
      expect(assigns(:scrap_list_item)).to be_a_new(ScrapListItem)
    end
  end

  describe "GET #edit" do
    it "assigns the requested scrap_list_item as @scrap_list_item" do
      scrap_list_item = ScrapListItem.create! valid_attributes
      get :edit, {:id => scrap_list_item.to_param}, valid_session
      expect(assigns(:scrap_list_item)).to eq(scrap_list_item)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ScrapListItem" do
        expect {
          post :create, {:scrap_list_item => valid_attributes}, valid_session
        }.to change(ScrapListItem, :count).by(1)
      end

      it "assigns a newly created scrap_list_item as @scrap_list_item" do
        post :create, {:scrap_list_item => valid_attributes}, valid_session
        expect(assigns(:scrap_list_item)).to be_a(ScrapListItem)
        expect(assigns(:scrap_list_item)).to be_persisted
      end

      it "redirects to the created scrap_list_item" do
        post :create, {:scrap_list_item => valid_attributes}, valid_session
        expect(response).to redirect_to(ScrapListItem.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved scrap_list_item as @scrap_list_item" do
        post :create, {:scrap_list_item => invalid_attributes}, valid_session
        expect(assigns(:scrap_list_item)).to be_a_new(ScrapListItem)
      end

      it "re-renders the 'new' template" do
        post :create, {:scrap_list_item => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested scrap_list_item" do
        scrap_list_item = ScrapListItem.create! valid_attributes
        put :update, {:id => scrap_list_item.to_param, :scrap_list_item => new_attributes}, valid_session
        scrap_list_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested scrap_list_item as @scrap_list_item" do
        scrap_list_item = ScrapListItem.create! valid_attributes
        put :update, {:id => scrap_list_item.to_param, :scrap_list_item => valid_attributes}, valid_session
        expect(assigns(:scrap_list_item)).to eq(scrap_list_item)
      end

      it "redirects to the scrap_list_item" do
        scrap_list_item = ScrapListItem.create! valid_attributes
        put :update, {:id => scrap_list_item.to_param, :scrap_list_item => valid_attributes}, valid_session
        expect(response).to redirect_to(scrap_list_item)
      end
    end

    context "with invalid params" do
      it "assigns the scrap_list_item as @scrap_list_item" do
        scrap_list_item = ScrapListItem.create! valid_attributes
        put :update, {:id => scrap_list_item.to_param, :scrap_list_item => invalid_attributes}, valid_session
        expect(assigns(:scrap_list_item)).to eq(scrap_list_item)
      end

      it "re-renders the 'edit' template" do
        scrap_list_item = ScrapListItem.create! valid_attributes
        put :update, {:id => scrap_list_item.to_param, :scrap_list_item => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested scrap_list_item" do
      scrap_list_item = ScrapListItem.create! valid_attributes
      expect {
        delete :destroy, {:id => scrap_list_item.to_param}, valid_session
      }.to change(ScrapListItem, :count).by(-1)
    end

    it "redirects to the scrap_list_items list" do
      scrap_list_item = ScrapListItem.create! valid_attributes
      delete :destroy, {:id => scrap_list_item.to_param}, valid_session
      expect(response).to redirect_to(scrap_list_items_url)
    end
  end

end
